import type { Contributor, HymnEntry, ThemeOption } from './types';

export const eras = [
  'Before 1700',
  '18th Century',
  '19th Century',
  '20th Century',
  '21st Century',
] as const;

export const meters = [
  'CM (8 6 8 6)',
  'CMD (8 6 8 6 D)',
  'HM (6 6 6 6 8 8)',
  'LM (8 8 8 8)',
  'LMD (8 8 8 8 D)',
  'LPM (8 8 8 8 8 8)',
  'SM (6 6 8 6)',
  'SMD (6 6 8 6 D)',
  'SPM (6 6 8 6 6 8)',
  'Other Meters',
] as const;

export const themeOptions: ThemeOption[] = [
  { label: 'Call to Worship', selectable: true },
  { label: 'Adoration & Praise', selectable: true },
  { label: "God's Perfections", selectable: false },
  { label: "God's Eternity", selectable: true, depth: 1 },
  { label: "God's Immutability", selectable: true, depth: 1 },
  { label: "God's Independence", selectable: true, depth: 1 },
  { label: "God's Omnipresence", selectable: true, depth: 1 },
  { label: "God's Omniscience", selectable: true, depth: 1 },
  { label: "God's Sovereignty", selectable: true, depth: 1 },
  { label: "God's Faithfulness", selectable: true, depth: 1 },
  { label: "God's Forgiveness", selectable: true, depth: 1 },
  { label: "God's Goodness", selectable: true, depth: 1 },
  { label: "God's Grace", selectable: true, depth: 1 },
  { label: "God's Holiness", selectable: true, depth: 1 },
  { label: "God's Justice", selectable: true, depth: 1 },
  { label: "God's Love", selectable: true, depth: 1 },
  { label: "God's Lovingkindness", selectable: true, depth: 1 },
  { label: "God's Mercy", selectable: true, depth: 1 },
  { label: "God's Patience", selectable: true, depth: 1 },
  { label: "God's Righteousness", selectable: true, depth: 1 },
  { label: "God's Truthfulness", selectable: true, depth: 1 },
  { label: "God's Word", selectable: true, depth: 1 },
  { label: 'The Holy Trinity', selectable: true },
  { label: 'God the Father', selectable: true },
  { label: 'God the Son', selectable: false },
  { label: 'The Person of Christ', selectable: true, depth: 1 },
  { label: 'The Incarnation', selectable: true, depth: 1 },
  { label: "The Savior's Sacrifice", selectable: true, depth: 1 },
  { label: 'The Risen Lord', selectable: true, depth: 1 },
  { label: "Christ's Return", selectable: true, depth: 1 },
  { label: 'The Reigning King', selectable: true, depth: 1 },
  { label: 'God the Holy Spirit', selectable: true },
  { label: 'Creation', selectable: true },
  { label: 'Providence', selectable: true },
  { label: 'Redemption', selectable: true },
  { label: 'The Christian Life', selectable: false },
  { label: 'Conversion & Calling', selectable: true, depth: 1 },
  { label: 'Prayer', selectable: true, depth: 1 },
  { label: 'Faith & Dependence', selectable: true, depth: 1 },
  { label: 'Assurance & Security', selectable: true, depth: 1 },
  { label: 'Devotion to Christ', selectable: true, depth: 1 },
  { label: 'Gratitude & Thanksgiving', selectable: true, depth: 1 },
  { label: 'Hope & Heaven', selectable: true, depth: 1 },
  { label: 'The Church', selectable: false },
  { label: 'The Bride of Christ', selectable: true, depth: 1 },
  { label: 'Christian Mission', selectable: true, depth: 1 },
  { label: 'Christian Community', selectable: true, depth: 1 },
  { label: 'Baptism', selectable: true, depth: 1 },
  { label: "The Lord's Supper", selectable: true, depth: 1 },
  { label: 'Revival', selectable: true },
  { label: 'Benediction', selectable: true },
  { label: 'Evening Meditations', selectable: true },
];

const selectableThemes = themeOptions
  .filter((theme) => theme.selectable)
  .map((theme) => theme.label);

function contributor(displayName: string, sortName: string, roles: Contributor['roles']): Contributor {
  return { displayName, sortName, roles };
}

function copyright(wordsPublicDomain: boolean, musicPublicDomain: boolean): HymnEntry['copyright'] {
  return { wordsPublicDomain, musicPublicDomain };
}

const handcraftedEntries: HymnEntry[] = [
  {
    id: 'hymn-001',
    number: 1,
    title: 'Doxology',
    firstLine: 'Praise God from whom all blessings flow',
    tuneName: 'OLD HUNDREDTH',
    meter: 'LM (8 8 8 8)',
    era: 'Before 1700',
    themes: ['Adoration & Praise'],
    contributors: [
      contributor('Thomas Ken', 'Ken, Thomas', ['words']),
      contributor('Louis Bourgeois', 'Bourgeois, Louis', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-002',
    number: 2,
    title: 'Holy, Holy, Holy',
    firstLine: 'Holy, holy, holy, Lord God Almighty',
    tuneName: 'NICAEA',
    meter: 'Other Meters',
    era: '19th Century',
    themes: ['The Holy Trinity'],
    contributors: [
      contributor('Reginald Heber', 'Heber, Reginald', ['words']),
      contributor('John B. Dykes', 'Dykes, John B.', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-003',
    number: 3,
    title: 'Praise to the Lord, the Almighty',
    firstLine: 'Praise to the Lord, the Almighty',
    tuneName: 'LOBE DEN HERREN',
    meter: 'Other Meters',
    era: 'Before 1700',
    themes: ['Adoration & Praise'],
    contributors: [
      contributor('Joachim Neander', 'Neander, Joachim', ['words']),
      contributor('Stralsund Gesangbuch', 'Stralsund Gesangbuch', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-004',
    number: 4,
    title: 'All Creatures of Our God and King',
    firstLine: 'All creatures of our God and King',
    tuneName: 'LASST UNS ERFREUEN',
    meter: 'Other Meters',
    era: 'Before 1700',
    themes: ['Creation'],
    contributors: [
      contributor('Francis of Assisi', 'Francis of Assisi', ['words']),
      contributor('Geistliche Kirchengesange', 'Geistliche Kirchengesange', ['music']),
      contributor('William H. Draper', 'Draper, William H.', ['translator']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-005',
    number: 5,
    title: 'A Mighty Fortress Is Our God',
    firstLine: 'A mighty fortress is our God',
    tuneName: 'EIN FESTE BURG',
    meter: 'Other Meters',
    era: 'Before 1700',
    themes: ["God's Sovereignty"],
    contributors: [contributor('Martin Luther', 'Luther, Martin', ['words', 'music'])],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-006',
    number: 6,
    title: 'Come, Thou Fount of Every Blessing',
    firstLine: 'Come, Thou Fount of every blessing',
    tuneName: 'NETTLETON',
    meter: 'Other Meters',
    era: '18th Century',
    themes: ['Devotion to Christ'],
    contributors: [
      contributor('Robert Robinson', 'Robinson, Robert', ['words']),
      contributor('John Wyeth', 'Wyeth, John', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-007',
    number: 7,
    title: 'O for a Thousand Tongues to Sing',
    firstLine: 'O for a thousand tongues to sing',
    tuneName: 'AZMON',
    meter: 'CM (8 6 8 6)',
    era: '18th Century',
    themes: ['Adoration & Praise'],
    contributors: [
      contributor('Charles Wesley', 'Wesley, Charles', ['words']),
      contributor('Lowell Mason', 'Mason, Lowell', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-008',
    number: 8,
    title: 'All Hail the Power of Jesus Name',
    firstLine: 'All hail the power of Jesus name',
    tuneName: 'CORONATION',
    meter: 'CM (8 6 8 6)',
    era: '18th Century',
    themes: ['The Reigning King'],
    contributors: [
      contributor('Edward Perronet', 'Perronet, Edward', ['words']),
      contributor('Oliver Holden', 'Holden, Oliver', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-009',
    number: 9,
    title: 'Crown Him with Many Crowns',
    firstLine: 'Crown Him with many crowns',
    tuneName: 'DIADEMATA',
    meter: 'SMD (6 6 8 6 D)',
    era: '19th Century',
    themes: ['The Reigning King'],
    contributors: [
      contributor('Matthew Bridges', 'Bridges, Matthew', ['words']),
      contributor('Godfrey Thring', 'Thring, Godfrey', ['words']),
      contributor('George J. Elvey', 'Elvey, George J.', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-010',
    number: 10,
    title: 'To God Be the Glory',
    firstLine: 'To God be the glory',
    chorusFirstLine: 'Praise the Lord, praise the Lord',
    tuneName: 'TO GOD BE THE GLORY',
    meter: 'Other Meters',
    era: '19th Century',
    themes: ['Adoration & Praise'],
    contributors: [
      contributor('Fanny J. Crosby', 'Crosby, Fanny J.', ['words']),
      contributor('William H. Doane', 'Doane, William H.', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-016',
    number: 16,
    title: 'How Firm a Foundation',
    firstLine: 'How firm a foundation',
    tuneName: 'FOUNDATION',
    meter: 'Other Meters',
    era: '18th Century',
    themes: ["God's Word"],
    contributors: [
      contributor('K. in Rippons Selection', 'K. in Rippons Selection', ['words']),
      contributor('Joseph Funk', 'Funk, Joseph', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-023',
    number: 23,
    title: 'When I Survey the Wondrous Cross',
    firstLine: 'When I survey the wondrous cross',
    tuneName: 'HAMBURG',
    meter: 'LM (8 8 8 8)',
    era: '18th Century',
    themes: ["The Savior's Sacrifice"],
    contributors: [
      contributor('Isaac Watts', 'Watts, Isaac', ['words']),
      contributor('Lowell Mason', 'Mason, Lowell', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-042',
    number: 42,
    title: 'Amazing Grace',
    firstLine: 'Amazing grace, how sweet the sound',
    tuneName: 'NEW BRITAIN',
    meter: 'CM (8 6 8 6)',
    era: '18th Century',
    themes: ["God's Grace"],
    contributors: [
      contributor('John Newton', 'Newton, John', ['words']),
      contributor('Virginia Harmony', 'Virginia Harmony', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-087',
    number: 87,
    title: 'Rock of Ages, Cleft for Me',
    firstLine: 'Rock of Ages, cleft for me',
    tuneName: 'TOPLADY',
    meter: 'Other Meters',
    era: '18th Century',
    themes: ["The Savior's Sacrifice"],
    contributors: [
      contributor('Augustus M. Toplady', 'Toplady, Augustus M.', ['words']),
      contributor('Thomas Hastings', 'Hastings, Thomas', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-118',
    number: 118,
    title: 'There Is a Fountain Filled with Blood',
    firstLine: 'There is a fountain filled with blood',
    tuneName: 'CLEANSING FOUNTAIN',
    meter: 'CM (8 6 8 6)',
    era: '18th Century',
    themes: ['Redemption'],
    contributors: [
      contributor('William Cowper', 'Cowper, William', ['words']),
      contributor('American melody', 'American melody', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-146',
    number: 146,
    title: 'Jesus, Lover of My Soul',
    firstLine: 'Jesus, Lover of my soul',
    tuneName: 'ABERYSTWYTH',
    meter: 'Other Meters',
    era: '18th Century',
    themes: ['Faith & Dependence'],
    contributors: [
      contributor('Charles Wesley', 'Wesley, Charles', ['words']),
      contributor('Joseph Parry', 'Parry, Joseph', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-174',
    number: 174,
    title: 'Guide Me, O Thou Great Jehovah',
    firstLine: 'Guide me, O Thou great Jehovah',
    tuneName: 'CWM RHONDDA',
    meter: 'Other Meters',
    era: '18th Century',
    themes: ['Faith & Dependence'],
    contributors: [
      contributor('William Williams', 'Williams, William', ['words']),
      contributor('John Hughes', 'Hughes, John', ['music']),
      contributor('Peter Williams', 'Williams, Peter', ['translator']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-205',
    number: 205,
    title: 'And Can It Be',
    firstLine: 'And can it be that I should gain',
    tuneName: 'SAGINA',
    meter: 'Other Meters',
    era: '18th Century',
    themes: ['Redemption'],
    contributors: [
      contributor('Charles Wesley', 'Wesley, Charles', ['words']),
      contributor('Thomas Campbell', 'Campbell, Thomas', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-227',
    number: 227,
    title: 'It Is Well with My Soul',
    firstLine: 'When peace like a river attendeth',
    chorusFirstLine: 'It is well with my soul',
    tuneName: 'VILLE DU HAVRE',
    meter: 'Other Meters',
    era: '19th Century',
    themes: ['Assurance & Security'],
    contributors: [
      contributor('Horatio G. Spafford', 'Spafford, Horatio G.', ['words']),
      contributor('Philip P. Bliss', 'Bliss, Philip P.', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-302',
    number: 302,
    title: 'Just As I Am',
    firstLine: 'Just as I am, without one plea',
    tuneName: 'WOODWORTH',
    meter: 'LM (8 8 8 8)',
    era: '19th Century',
    themes: ['Conversion & Calling'],
    contributors: [
      contributor('Charlotte Elliott', 'Elliott, Charlotte', ['words']),
      contributor('William B. Bradbury', 'Bradbury, William B.', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-365',
    number: 365,
    title: 'Be Thou My Vision',
    firstLine: 'Be Thou my vision, O Lord',
    tuneName: 'SLANE',
    meter: 'Other Meters',
    era: 'Before 1700',
    themes: ['Devotion to Christ'],
    contributors: [
      contributor('Ancient Irish hymn', 'Ancient Irish hymn', ['words']),
      contributor('Traditional Irish melody', 'Traditional Irish melody', ['music']),
      contributor('Eleanor H. Hull', 'Hull, Eleanor H.', ['translator']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-390',
    number: 390,
    title: 'What a Friend We Have in Jesus',
    firstLine: 'What a friend we have in Jesus',
    tuneName: 'CONVERSE',
    meter: 'CMD (8 6 8 6 D)',
    era: '19th Century',
    themes: ['Prayer'],
    contributors: [
      contributor('Joseph M. Scriven', 'Scriven, Joseph M.', ['words']),
      contributor('Charles C. Converse', 'Converse, Charles C.', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-418',
    number: 418,
    title: 'Blessed Assurance',
    firstLine: 'Blessed assurance, Jesus is mine',
    chorusFirstLine: 'This is my story, this is my song',
    tuneName: 'ASSURANCE',
    meter: 'Other Meters',
    era: '19th Century',
    themes: ['Assurance & Security'],
    contributors: [
      contributor('Fanny J. Crosby', 'Crosby, Fanny J.', ['words']),
      contributor('Phoebe P. Knapp', 'Knapp, Phoebe P.', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-444',
    number: 444,
    title: 'I Need Thee Every Hour',
    firstLine: 'I need Thee every hour',
    tuneName: 'NEED',
    meter: 'Other Meters',
    era: '19th Century',
    themes: ['Prayer'],
    contributors: [
      contributor('Annie S. Hawks', 'Hawks, Annie S.', ['words']),
      contributor('Robert Lowry', 'Lowry, Robert', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-472',
    number: 472,
    title: 'My Hope Is Built on Nothing Less',
    firstLine: 'My hope is built on nothing less',
    chorusFirstLine: 'On Christ the solid Rock I stand',
    tuneName: 'SOLID ROCK',
    meter: 'Other Meters',
    era: '19th Century',
    themes: ['Faith & Dependence'],
    contributors: [
      contributor('Edward Mote', 'Mote, Edward', ['words']),
      contributor('William B. Bradbury', 'Bradbury, William B.', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-512',
    number: 512,
    title: 'Take My Life and Let It Be',
    firstLine: 'Take my life and let it be',
    tuneName: 'HENDON',
    meter: 'Other Meters',
    era: '19th Century',
    themes: ['Devotion to Christ'],
    contributors: [
      contributor('Frances R. Havergal', 'Havergal, Frances R.', ['words']),
      contributor('Henri A. C. Malan', 'Malan, Henri A. C.', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-521',
    number: 521,
    title: 'There Is a Balm in Gilead',
    firstLine: 'There is a balm in Gilead',
    tuneName: 'BALM IN GILEAD',
    meter: 'CMD (8 6 8 6 D)',
    era: '19th Century',
    themes: ['Hope & Heaven'],
    contributors: [contributor('African American spiritual', 'African American spiritual', ['words', 'music'])],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-540',
    number: 540,
    title: 'Leaning on the Everlasting Arms',
    firstLine: 'Leaning on the everlasting arms',
    chorusFirstLine: 'Leaning, leaning, safe and secure',
    tuneName: 'SHOWALTER',
    meter: 'Other Meters',
    era: '19th Century',
    themes: ['Assurance & Security'],
    contributors: [
      contributor('Elisha A. Hoffman', 'Hoffman, Elisha A.', ['words']),
      contributor('Anthony J. Showalter', 'Showalter, Anthony J.', ['music']),
    ],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-558',
    number: 558,
    title: 'Standing on the Promises',
    firstLine: 'Standing on the promises of Christ',
    chorusFirstLine: 'Standing, standing, standing on the promises',
    tuneName: 'PROMISES',
    meter: 'Other Meters',
    era: '19th Century',
    themes: ['Faith & Dependence'],
    contributors: [contributor('R. Kelso Carter', 'Carter, R. Kelso', ['words', 'music'])],
    copyright: copyright(true, true),
  },
  {
    id: 'hymn-573',
    number: 573,
    title: 'In the Garden',
    firstLine: 'I come to the garden alone',
    tuneName: 'GARDEN',
    meter: 'Other Meters',
    era: '20th Century',
    themes: ['Christian Community'],
    contributors: [contributor('C. Austin Miles', 'Miles, C. Austin', ['words', 'music'])],
    copyright: copyright(true, true),
  },
];

const firstNames = [
  'Abel',
  'Ada',
  'Benedict',
  'Celia',
  'Daniel',
  'Edith',
  'Frederick',
  'Grace',
  'Hugh',
  'Iris',
  'Jonas',
  'Lydia',
  'Martin',
  'Nora',
  'Owen',
  'Phoebe',
  'Rufus',
  'Susanna',
  'Theodore',
  'Viola',
  'Warren',
  'Yvonne',
  'Zachary',
];

const lastNames = [
  'Alcott',
  'Bramwell',
  'Cairn',
  'Davenport',
  'Ellison',
  'Fairchild',
  'Gresham',
  'Hartwell',
  'Ingram',
  'Jessel',
  'Kingsley',
  'Lowell',
  'Marden',
  'Norcross',
  'Orchard',
  'Prescott',
  'Quillen',
  'Ravenscroft',
  'Stillman',
  'Taverner',
  'Underhill',
  'Verity',
  'Winslow',
  'Yardley',
];

const titleOpeners = [
  'A Song for',
  'Behold the',
  'Come Praise the',
  'From Every',
  'Great Is the',
  'Let Zion',
  'O Blessed',
  'The Mercy of',
  'When Morning',
  'With Quiet',
];

const titleSubjects = [
  'Faithful Shepherd',
  'King of Grace',
  'Living Word',
  'Lord of Harvest',
  'Pilgrim Hope',
  'Risen Savior',
  'Steadfast Love',
  'Table of Peace',
  'Throne of Glory',
  'Voice of Mercy',
];

const firstLineOpeners = [
  'Across the fields of morning',
  'Before the mercy seat',
  'Beneath the quiet heavens',
  'Come lift the ancient promise',
  'From every shaded valley',
  'In every hour of waiting',
  'Let every heart remember',
  'O keep us near the Savior',
  'The saints in hope are singing',
  'When evening gathers softly',
];

const tuneRoots = [
  'ABBEY GATE',
  'BRIGHT MEADOW',
  'CEDAR HALL',
  'DOVEWELL',
  'ELM COMMON',
  'FAIRHAVEN',
  'GRACEFIELD',
  'HARBOR ROAD',
  'IVORY LANE',
  'KINGSMEAD',
  'LOWLAND',
  'MERCY HILL',
  'NORTH CHAPEL',
  'OAK PARISH',
  'PRAISEWELL',
  'QUIET VALE',
];

function makeGeneratedContributor(seed: number, role: Contributor['roles'][number]): Contributor {
  const firstName = firstNames[seed % firstNames.length];
  const lastName = lastNames[Math.floor(seed / firstNames.length) % lastNames.length];
  return contributor(`${firstName} ${lastName}`, `${lastName}, ${firstName}`, [role]);
}

function makeGeneratedEntry(number: number, index: number): HymnEntry {
  const title = `${titleOpeners[index % titleOpeners.length]} ${
    titleSubjects[Math.floor(index / titleOpeners.length) % titleSubjects.length]
  }`;
  const firstLine = `${firstLineOpeners[index % firstLineOpeners.length]}, we trace the Lord's kindness`;
  const theme = selectableThemes[index % selectableThemes.length];
  const tuneName = `${tuneRoots[index % tuneRoots.length]} ${String((index % 9) + 1)}`;
  const words = makeGeneratedContributor(index * 2, 'words');
  const music = index % 13 === 0 ? words : makeGeneratedContributor(index * 2 + 1, 'music');

  return {
    id: `hymn-${String(number).padStart(3, '0')}`,
    number,
    title,
    firstLine,
    chorusFirstLine: index % 6 === 0 ? 'Sing praise, sing praise, the covenant stands sure' : undefined,
    tuneName,
    meter: meters[index % meters.length],
    era: eras[index % eras.length],
    themes: [theme],
    contributors: music === words ? [words] : [words, music],
    copyright: copyright(index % 3 === 0, index % 4 === 0),
  };
}

export function buildDummyHymnCatalog(): HymnEntry[] {
  const handcraftedNumbers = new Set(handcraftedEntries.map((entry) => entry.number));
  const generatedEntries: HymnEntry[] = [];

  for (let number = 1; number <= 573; number += 1) {
    if (!handcraftedNumbers.has(number)) {
      generatedEntries.push(makeGeneratedEntry(number, generatedEntries.length));
    }
  }

  return [...handcraftedEntries, ...generatedEntries].sort((a, b) => a.number - b.number);
}

export const hymnCatalog = buildDummyHymnCatalog();
